# Reproducible Research: Peer Assessment 1
# Paul Reiners


## Loading and preprocessing the data
activity = read.csv("activity.csv")
activity$date <- as.Date(activity$date, format = "%Y-%m-%d")


## What is mean total number of steps taken per day?
daily.steps <- 
        aggregate(activity$steps, by=list(activity$date), FUN=sum, na.rm=TRUE)
colnames(daily.steps) <- c("date", "steps")
hist(daily.steps$steps, main="Daily Steps", xlab="Number of steps")
mean(daily.steps$steps)
median(daily.steps$steps)


## What is the average daily activity pattern?
daily.activity <- 
        aggregate(
                activity$steps, by=list(activity$interval), FUN=mean, 
                na.rm=TRUE)
colnames(daily.activity) = c("interval", "steps")
plot(
        daily.activity$interval, daily.activity$steps, type = "l", 
        xlab="5-minute interval", ylab="Average number of steps")
daily.activity$interval[which.max(daily.activity$steps)]

## Imputing missing values
nrow(activity) - sum(complete.cases(activity))


## Are there differences in activity patterns between weekdays and weekends?
